server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
            allowedHeaders: "*"


      routes:
        - id: core-service
          uri: http://localhost:8189
          predicates:
            - Path=/core/api/v1/products
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
        - id: core-service
          uri: http://localhost:8189
          predicates:
            - Path=/core/api/v1/orders/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
        - id: core-service
          uri: http://localhost:8189
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8190
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-carts
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8190
          predicates:
            - Path=/auth/auth_check
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8190
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter