server:
  port: 8188
  servlet:
    context-path: /market-carts
integrations:
  product-service:
    url: hhtp://localhost:8189/market-core/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000
  cart-service:
    cart-prefix: cart_