server:
  port: 8189
  servlet:
    context-path: /market-core
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  integrations:
    product-service:
      url: hhtp://localhost:8189/market-carts/
      read-timeout: 10000
      write-timeout: 5000
      connect-timeout: 5000
